name = input( "What is your name: " )
age = int( input( "How old are you: " ) )
year = str( ( 2024 - age ) + 100 )
print ("{}will turn 100 in the year {}".format(name, year))
print( name + " will be 100 years old in the year " + year )