--Activity1
CREATE TABLE salesman(
    salesman_id int,
    salesman_name varchar(20),
    salesman_city varchar(20),
    commission int
);

DESCRIBE SALESMAN

--Activity2
INSERT INTO SALESMAN(SALESMAN_ID,SALESMAN_NAME,SALESMAN_CITY,COMMISSION)
VALUES (5001,'James Hoog','Newyork',15);
INSERT INTO SALESMAN
VALUES (5002,'Nail Knite','Paris',13);
INSERT INTO SALESMAN
VALUES (5005,'Pit Alex','London',11);
INSERT INTO SALESMAN
VALUES (5006,'McLyon','Paris',14);
INSERT INTO SALESMAN
VALUES (5007,'Paul Adam','Rome',13);
INSERT INTO SALESMAN
VALUES (5003,'Lauson Hen','San Jose',12);

SELECT * FROM SALESMAN;

--Activity3
SELECT SALESMAN_ID,SALESMAN_CITY FROM SALESMAN;

SELECT * FROM SALESMAN WHERE SALESMAN_CITY ='Paris';

SELECT SALESMAN_ID,COMMISSION FROM SALESMAN WHERE SALESMAN_NAME = 'Paul Adam';

SELECT * FROM SALESMAN WHERE COMMISSION >= 13;

SELECT * FROM SALESMAN WHERE SALESMAN_ID IN (5002,5005);

SELECT SALESMAN_NAME
FROM SALESMAN WHERE SALESMAN_NAME LIKE 'P%' ;

--Activity4
ALTER TABLE SALESMAN ADD GRADE INT;

UPDATE SALESMAN SET GRADE = 100;

SELECT * FROM SALESMAN;

--Activity5

UPDATE SALESMAN SET GRADE = 200 WHERE SALESMAN_CITY = 'Rome';

UPDATE SALESMAN SET GRADE = 300 WHERE SALESMAN_NAME = 'James Hoog';

UPDATE SALESMAN SET SALESMAN_NAME = 'Pierre' WHERE SALESMAN_NAME = 'McLyon';

SELECT * FROM SALESMAN;
